//! The Zephyr dictionary logging database.
//!
//! The database is generated by `scripts/logging/dictionary/database_gen.py` in the Zephyr tree
//! and describes the target (endianness, pointer width, architecture), the log sources and the
//! strings that log messages refer to by address.

use std::collections::HashMap;
use std::io::Read;

use anyhow::{Context, bail};
use base64::Engine;
use serde::Deserialize;

/// The database version this decoder supports, `ZEPHYR_DICT_LOG_VER` in the Zephyr tree.
const SUPPORTED_VERSION: u32 = 3;

/// Name of the ELF section that Zephyr embeds the database into
/// (`CONFIG_LOG_DICTIONARY_DB_EMBED`).
pub const EMBEDDED_DB_SECTION: &str = ".zephyr_log_dict";

#[derive(Deserialize)]
struct RawDatabase {
    version: u32,
    target: RawTarget,
    arch: String,
    #[serde(default)]
    build_id: Option<String>,
    #[serde(default)]
    kconfigs: HashMap<String, i64>,
    log_subsys: RawLogSubsys,
    #[serde(default)]
    string_mappings: HashMap<String, String>,
    #[serde(default)]
    sections: HashMap<String, RawSection>,
}

#[derive(Deserialize)]
struct RawTarget {
    little_endianness: bool,
    bits: u32,
}

#[derive(Deserialize)]
struct RawLogSubsys {
    #[serde(default)]
    log_instances: HashMap<String, RawLogInstance>,
}

#[derive(Deserialize)]
struct RawLogInstance {
    name: String,
}

#[derive(Deserialize)]
struct RawSection {
    start: u64,
    data_b64: String,
}

struct StringSection {
    start: u64,
    data: Vec<u8>,
}

pub struct Database {
    pub(super) little_endian: bool,
    pub(super) is_64bit: bool,
    pub(super) arch: String,
    pub(super) timestamp_64bit: bool,
    build_id: Option<String>,
    kconfigs: HashMap<String, i64>,
    sources: HashMap<u64, String>,
    /// Strings by address, sorted by address.
    strings: Vec<(u64, String)>,
    sections: Vec<StringSection>,
}

impl std::fmt::Debug for Database {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Database")
            .field("arch", &self.arch)
            .field("build_id", &self.build_id)
            .finish_non_exhaustive()
    }
}

/// Converts a string from the JSON database back to its original bytes and decodes them as UTF-8.
///
/// The generator reads target strings byte by byte into Latin-1 code points, so UTF-8 strings
/// in the firmware would otherwise be displayed garbled.
fn decode_latin1(s: &str) -> String {
    if s.is_ascii() {
        return s.to_string();
    }

    match s.chars().map(u8::try_from).collect::<Result<Vec<u8>, _>>() {
        Ok(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
        Err(_) => s.to_string(),
    }
}

impl Database {
    /// JSON, optionally gzip-compressed.
    pub fn from_bytes(data: &[u8]) -> anyhow::Result<Self> {
        if data.starts_with(&[0x1f, 0x8b]) {
            let mut json = Vec::new();
            flate2::read::GzDecoder::new(data)
                .read_to_end(&mut json)
                .context("Failed to decompress the Zephyr log dictionary database")?;
            Self::from_json(&json)
        } else {
            Self::from_json(data)
        }
    }

    /// Loads the database embedded into a Zephyr ELF file, if there is one.
    pub fn from_elf(elf: &[u8]) -> anyhow::Result<Option<Self>> {
        use object::{Object, ObjectSection};

        let Ok(file) = object::File::parse(elf) else {
            return Ok(None);
        };
        let Some(section) = file.section_by_name(EMBEDDED_DB_SECTION) else {
            return Ok(None);
        };
        let data = section
            .data()
            .context("Failed to read the embedded Zephyr log dictionary database")?;

        Self::from_bytes(data).map(Some)
    }

    fn from_json(json: &[u8]) -> anyhow::Result<Self> {
        let raw: RawDatabase = serde_json::from_slice(json)
            .context("Failed to parse the Zephyr log dictionary database")?;

        if raw.version != SUPPORTED_VERSION {
            bail!(
                "Unsupported Zephyr log dictionary database version {} (supported: {SUPPORTED_VERSION})",
                raw.version
            );
        }

        let is_64bit = match raw.target.bits {
            32 => false,
            64 => true,
            bits => bail!("Unsupported target word size in log dictionary database: {bits} bits"),
        };

        let sources = raw
            .log_subsys
            .log_instances
            .into_iter()
            .filter_map(|(id, instance)| Some((id.parse().ok()?, decode_latin1(&instance.name))))
            .collect();

        let mut strings = raw
            .string_mappings
            .into_iter()
            .filter_map(|(addr, s)| Some((addr.parse().ok()?, decode_latin1(&s))))
            .collect::<Vec<_>>();
        strings.sort_by_key(|(addr, _)| *addr);

        let sections = raw
            .sections
            .into_values()
            .map(|section| {
                let data = base64::engine::general_purpose::STANDARD
                    .decode(section.data_b64)
                    .context("Invalid section data in log dictionary database")?;
                Ok(StringSection {
                    start: section.start,
                    data,
                })
            })
            .collect::<anyhow::Result<_>>()?;

        Ok(Self {
            little_endian: raw.target.little_endianness,
            is_64bit,
            timestamp_64bit: raw.kconfigs.contains_key("CONFIG_LOG_TIMESTAMP_64BIT"),
            arch: raw.arch,
            build_id: raw.build_id,
            kconfigs: raw.kconfigs,
            sources,
            strings,
            sections,
        })
    }

    /// The Zephyr build the database belongs to.
    pub fn build_id(&self) -> Option<&str> {
        self.build_id.as_deref()
    }

    /// The RTT up channel the RTT logging backend outputs dictionary logs on, if the database
    /// records it.
    pub fn rtt_channel(&self) -> Option<u32> {
        if self
            .kconfigs
            .get("CONFIG_LOG_BACKEND_RTT_OUTPUT_DICTIONARY")
            != Some(&1)
        {
            return None;
        }

        self.kconfigs
            .get("CONFIG_LOG_BACKEND_RTT_BUFFER")
            .and_then(|&channel| u32::try_from(channel).ok())
    }

    /// Whether the RTT logging backend outputs the logs as hexadecimal text, if the database
    /// records it.
    pub fn rtt_hex(&self) -> Option<bool> {
        self.rtt_channel()?;

        Some(
            self.kconfigs
                .get("CONFIG_LOG_BACKEND_RTT_OUTPUT_DICTIONARY_HEX")
                == Some(&1),
        )
    }

    pub fn source_name(&self, domain_id: u8, source_id: u64) -> String {
        match self.sources.get(&source_id) {
            Some(name) => name.clone(),
            None => format!("unknown<{domain_id}:{source_id}>"),
        }
    }

    pub fn find_string(&self, addr: u64) -> Option<String> {
        self.find_string_in_mappings(addr)
            .or_else(|| self.find_string_in_sections(addr))
    }

    fn find_string_in_mappings(&self, addr: u64) -> Option<String> {
        // The address may also point into a string, e.g. when the compiler merged the tail
        // of one string with another.
        let idx = self.strings.partition_point(|(start, _)| *start <= addr);
        let (start, s) = self.strings.get(idx.checked_sub(1)?)?;
        let offset = usize::try_from(addr - start).ok()?;

        if offset == 0 {
            Some(s.clone())
        } else {
            s.get(offset..)
                .filter(|tail| !tail.is_empty())
                .map(str::to_string)
        }
    }

    fn find_string_in_sections(&self, addr: u64) -> Option<String> {
        self.sections.iter().find_map(|section| {
            let offset = usize::try_from(addr.checked_sub(section.start)?).ok()?;
            let data = section.data.get(offset..).filter(|data| !data.is_empty())?;
            let end = data.iter().position(|&b| b == 0).unwrap_or(data.len());

            Some(String::from_utf8_lossy(&data[..end]).into_owned())
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn db(extra: &str) -> Database {
        Database::from_bytes(
            format!(
                r#"{{
                    "version": 3,
                    "target": {{ "little_endianness": true, "bits": 32 }},
                    "arch": "arm",
                    "log_subsys": {{ "log_instances": {{ "2": {{ "source_id": 2, "name": "app", "level": 3, "addr": 100 }} }} }},
                    "string_mappings": {{ "1000": "hello world", "2000": "Ã©tÃ©" }}
                    {extra}
                }}"#
            )
            .as_bytes(),
        )
        .unwrap()
    }

    #[test]
    fn strings_by_address() {
        let db = db("");

        assert_eq!(db.find_string(1000).as_deref(), Some("hello world"));
        assert_eq!(db.find_string(1006).as_deref(), Some("world"));
        assert_eq!(db.find_string(999), None);
        assert_eq!(db.find_string(1011), None);
        assert_eq!(db.find_string(2000).as_deref(), Some("été"));
    }

    #[test]
    fn strings_in_sections() {
        // "abc\0def\0" at 0x3000
        let db = db(
            r#", "sections": { "rodata": { "name": "rodata", "start": 12288, "end": 12296, "size": 8, "data_b64": "YWJjAGRlZgA=" } }"#,
        );

        assert_eq!(db.find_string(0x3000).as_deref(), Some("abc"));
        assert_eq!(db.find_string(0x3004).as_deref(), Some("def"));
        assert_eq!(db.find_string(0x3008), None);
    }

    #[test]
    fn sources() {
        let db = db("");

        assert_eq!(db.source_name(0, 2), "app");
        assert_eq!(db.source_name(1, 7), "unknown<1:7>");
    }

    #[test]
    fn rtt_settings() {
        assert_eq!(db("").rtt_channel(), None);

        let db = db(
            r#", "kconfigs": { "CONFIG_LOG_BACKEND_RTT_OUTPUT_DICTIONARY": 1, "CONFIG_LOG_BACKEND_RTT_BUFFER": 2 }"#,
        );
        assert_eq!(db.rtt_channel(), Some(2));
        assert_eq!(db.rtt_hex(), Some(false));
    }

    #[test]
    fn gzip_compressed() {
        let json = br#"{ "version": 3, "target": { "little_endianness": false, "bits": 64 }, "arch": "arm64", "log_subsys": {} }"#;
        let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
        std::io::Write::write_all(&mut encoder, json).unwrap();

        let db = Database::from_bytes(&encoder.finish().unwrap()).unwrap();
        assert!(db.is_64bit);
        assert!(!db.little_endian);
    }

    #[test]
    fn unsupported_version() {
        let json = br#"{ "version": 1, "target": { "little_endianness": true, "bits": 32 }, "arch": "arm", "log_subsys": {} }"#;
        assert!(Database::from_bytes(json).is_err());
    }
}
