use super::{RegisterDataType, RegisterDescription, RegisterFile, RegisterKind, RegisterLocation};

const SP: RegisterDescription = RegisterDescription {
    name: "SP",
    _kind: RegisterKind::General,
    location: RegisterLocation(31),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 64,
};

const PC: RegisterDescription = RegisterDescription {
    name: "PC",
    _kind: RegisterKind::General,
    location: RegisterLocation(32),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 64,
};

const LR: RegisterDescription = RegisterDescription {
    name: "LR",
    _kind: RegisterKind::General,
    location: RegisterLocation(30),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 64,
};

const FP: RegisterDescription = RegisterDescription {
    name: "FP",
    _kind: RegisterKind::General,
    location: RegisterLocation(29),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 64,
};

const PSTATE: RegisterDescription = RegisterDescription {
    name: "PSTATE",
    _kind: RegisterKind::General,
    location: RegisterLocation(33),
    _type: RegisterDataType::UnsignedInteger,
    size_in_bits: 32,
};

pub static AARCH64_REGISTER_FILE: RegisterFile = RegisterFile {
    platform_registers: &[
        RegisterDescription {
            name: "X0",
            _kind: RegisterKind::General,
            location: RegisterLocation(0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X1",
            _kind: RegisterKind::General,
            location: RegisterLocation(1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X2",
            _kind: RegisterKind::General,
            location: RegisterLocation(2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X3",
            _kind: RegisterKind::General,
            location: RegisterLocation(3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X4",
            _kind: RegisterKind::General,
            location: RegisterLocation(4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X5",
            _kind: RegisterKind::General,
            location: RegisterLocation(5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X6",
            _kind: RegisterKind::General,
            location: RegisterLocation(6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X7",
            _kind: RegisterKind::General,
            location: RegisterLocation(7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X8",
            _kind: RegisterKind::General,
            location: RegisterLocation(8),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X9",
            _kind: RegisterKind::General,
            location: RegisterLocation(9),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X10",
            _kind: RegisterKind::General,
            location: RegisterLocation(10),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X11",
            _kind: RegisterKind::General,
            location: RegisterLocation(11),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X12",
            _kind: RegisterKind::General,
            location: RegisterLocation(12),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X13",
            _kind: RegisterKind::General,
            location: RegisterLocation(13),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X14",
            _kind: RegisterKind::General,
            location: RegisterLocation(14),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X15",
            _kind: RegisterKind::General,
            location: RegisterLocation(15),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X16",
            _kind: RegisterKind::General,
            location: RegisterLocation(16),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X17",
            _kind: RegisterKind::General,
            location: RegisterLocation(17),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X18",
            _kind: RegisterKind::General,
            location: RegisterLocation(18),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X19",
            _kind: RegisterKind::General,
            location: RegisterLocation(19),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X20",
            _kind: RegisterKind::General,
            location: RegisterLocation(20),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X21",
            _kind: RegisterKind::General,
            location: RegisterLocation(21),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X22",
            _kind: RegisterKind::General,
            location: RegisterLocation(22),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X23",
            _kind: RegisterKind::General,
            location: RegisterLocation(23),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X24",
            _kind: RegisterKind::General,
            location: RegisterLocation(24),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X25",
            _kind: RegisterKind::General,
            location: RegisterLocation(25),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X26",
            _kind: RegisterKind::General,
            location: RegisterLocation(26),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X27",
            _kind: RegisterKind::General,
            location: RegisterLocation(27),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X28",
            _kind: RegisterKind::General,
            location: RegisterLocation(28),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X29",
            _kind: RegisterKind::General,
            location: RegisterLocation(29),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "X30",
            _kind: RegisterKind::General,
            location: RegisterLocation(30),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "SP",
            _kind: RegisterKind::General,
            location: RegisterLocation(31),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "PC",
            _kind: RegisterKind::General,
            location: RegisterLocation(32),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
    ],

    program_counter: &PC,
    stack_pointer: &SP,
    return_address: &LR,
    frame_pointer: &FP,

    argument_registers: &[
        RegisterDescription {
            name: "a0",
            _kind: RegisterKind::General,
            location: RegisterLocation(0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "a1",
            _kind: RegisterKind::General,
            location: RegisterLocation(1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "a2",
            _kind: RegisterKind::General,
            location: RegisterLocation(2),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "a3",
            _kind: RegisterKind::General,
            location: RegisterLocation(3),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "a4",
            _kind: RegisterKind::General,
            location: RegisterLocation(4),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "a5",
            _kind: RegisterKind::General,
            location: RegisterLocation(5),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "a6",
            _kind: RegisterKind::General,
            location: RegisterLocation(6),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "a7",
            _kind: RegisterKind::General,
            location: RegisterLocation(7),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
    ],

    result_registers: &[
        RegisterDescription {
            name: "a0",
            _kind: RegisterKind::General,
            location: RegisterLocation(0),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
        RegisterDescription {
            name: "a1",
            _kind: RegisterKind::General,
            location: RegisterLocation(1),
            _type: RegisterDataType::UnsignedInteger,
            size_in_bits: 64,
        },
    ],

    msp: Some(&SP),
    psp: Some(&SP),
    extra: None,
    psr: Some(&PSTATE),
};
